// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudentManagerApi.Models;

public partial class Course
{
    public string CourseNumber { get; set; }

    public string CourseName { get; set; }

    public string Instructor { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public virtual ICollection<Registration> Registrations { get; } = new List<Registration>();
}