// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudentManagerApi.Models;

public partial class Student
{
    public int StudentId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Major { get; set; }

    public DateTime ExpectedGradDate { get; set; }

    public decimal Gpa { get; set; }

    public virtual ICollection<Registration> Registrations { get; } = new List<Registration>();
}